import type { EffectConfig, EffectId } from "@/lib/effects/types";
import type { TemplateId } from "@/lib/types";

export const EFFECTS: Record<EffectId, EffectConfig> = {
  // ---- Çiçek açma (bloom-spiral, Phyllotaxis: Altın Açı + sqrt) ----
  rose: {
    id: "rose",
    label: "Gül",
    emoji: "🌹",
    category: "bloom",
    particleShape: "petal",
    particleCount: 450,
    colorPalette: ["#e0396b", "#ff7aa2", "#ffc2d4"],
    motionPattern: "bloom-spiral",
    layerCount: 4,
    timing: { duration: 1.8, stagger: 0.008, ease: "power2.out" },
    spread: 42,
    size: 13,
  },
  peony: {
    id: "peony",
    label: "Şakayık",
    emoji: "🌸",
    category: "bloom",
    particleShape: "petal",
    particleCount: 52,
    colorPalette: ["#f9a8d4", "#f472b6", "#ec4899", "#fbcfe8"],
    motionPattern: "bloom-spiral",
    layerCount: 5,
    timing: { duration: 2.1, stagger: 0.05, ease: "power2.out" },
    spread: 56,
  },
  daisy: {
    id: "daisy",
    label: "Papatya",
    emoji: "🌼",
    category: "bloom",
    particleShape: "petal",
    particleCount: 30,
    colorPalette: ["#ffffff", "#fef9c3", "#fde047", "#ffedd5"],
    motionPattern: "bloom-spiral",
    layerCount: 3,
    timing: { duration: 1.5, stagger: 0.06, ease: "power2.out" },
    spread: 46,
  },
  tulip: {
    id: "tulip",
    label: "Lale",
    emoji: "🌷",
    category: "bloom",
    particleShape: "petal",
    particleCount: 34,
    colorPalette: ["#fb7185", "#fda4af", "#fecdd3", "#fff1f2"],
    motionPattern: "bloom-spiral",
    layerCount: 3,
    timing: { duration: 1.7, stagger: 0.055, ease: "power2.out" },
    spread: 50,
  },
  orchid: {
    id: "orchid",
    label: "Orkide",
    emoji: "🌺",
    category: "bloom",
    particleShape: "petal",
    particleCount: 38,
    colorPalette: ["#c084fc", "#a855f7", "#e9d5ff", "#d8b4fe"],
    motionPattern: "bloom-spiral",
    layerCount: 4,
    timing: { duration: 1.9, stagger: 0.05, ease: "power2.out" },
    spread: 54,
  },
  sunflower: {
    id: "sunflower",
    label: "Ayçiçeği",
    emoji: "🌻",
    category: "bloom",
    particleShape: "petal",
    particleCount: 56,
    colorPalette: ["#fbbf24", "#f59e0b", "#fcd34d", "#b45309"],
    motionPattern: "bloom-spiral",
    layerCount: 3,
    timing: { duration: 1.6, stagger: 0.045, ease: "power2.out" },
    spread: 52,
  },
  lily: {
    id: "lily",
    label: "Zambak",
    emoji: "🏵️",
    category: "bloom",
    particleShape: "petal",
    particleCount: 42,
    colorPalette: ["#fef08a", "#fde047", "#fef9c3", "#ffffff"],
    motionPattern: "bloom-spiral",
    layerCount: 4,
    timing: { duration: 1.8, stagger: 0.05, ease: "power2.out" },
    spread: 54,
  },
  magnolia: {
    id: "magnolia",
    label: "Manolya",
    emoji: "🌺",
    category: "bloom",
    particleShape: "petal",
    particleCount: 36,
    colorPalette: ["#fef3c7", "#fde68a", "#f8fafc", "#fecaca"],
    motionPattern: "bloom-spiral",
    layerCount: 4,
    timing: { duration: 2.0, stagger: 0.06, ease: "power2.out" },
    spread: 52,
  },
  daffodil: {
    id: "daffodil",
    label: "Nergis",
    emoji: "🌼",
    category: "bloom",
    particleShape: "petal",
    particleCount: 32,
    colorPalette: ["#fde047", "#fef08a", "#f8fafc", "#fdba74"],
    motionPattern: "bloom-spiral",
    layerCount: 3,
    timing: { duration: 1.5, stagger: 0.06, ease: "power2.out" },
    spread: 46,
  },
  cherryblossom: {
    id: "cherryblossom",
    label: "Kiraz Çiçeği",
    emoji: "🌸",
    category: "bloom",
    particleShape: "petal",
    particleCount: 46,
    colorPalette: ["#fda4af", "#fb7185", "#ffe4e6", "#fff1f2"],
    motionPattern: "bloom-spiral",
    layerCount: 3,
    timing: { duration: 1.7, stagger: 0.045, ease: "power2.out" },
    spread: 48,
  },

  // ---- Patlama / parçacık (burst-radial) ----
  heartburst: {
    id: "heartburst",
    label: "Kalp Patlaması",
    emoji: "💗",
    category: "burst",
    particleShape: "heart",
    particleCount: 40,
    colorPalette: ["#ff4d6d", "#ff7eb3", "#ff9ebc", "#ff6b8b"],
    motionPattern: "burst-radial",
    layerCount: 1,
    timing: { duration: 1.6, stagger: 0.02, ease: "power2.out" },
    spread: 60,
    size: 24,
  },
  confetti: {
    id: "confetti",
    label: "Konfeti Patlaması",
    emoji: "🎉",
    category: "burst",
    particleShape: "confetti",
    particleCount: 64,
    colorPalette: ["#f472b6", "#facc15", "#4ade80", "#60a5fa", "#fb923c"],
    motionPattern: "burst-radial",
    layerCount: 1,
    timing: { duration: 1.8, stagger: 0.015, ease: "power2.out" },
    spread: 68,
    size: 12,
  },
  stardust: {
    id: "stardust",
    label: "Yıldız Tozu",
    emoji: "✨",
    category: "burst",
    particleShape: "star",
    particleCount: 38,
    colorPalette: ["#fde047", "#fbbf24", "#fff7ed", "#fdba74"],
    motionPattern: "burst-radial",
    layerCount: 1,
    timing: { duration: 1.5, stagger: 0.02, ease: "power2.out" },
    spread: 56,
    size: 18,
  },
  balloon: {
    id: "balloon",
    label: "Balon Yükselişi",
    emoji: "🎈",
    category: "burst",
    particleShape: "balloon",
    particleCount: 16,
    colorPalette: ["#f472b6", "#fb7185", "#60a5fa", "#facc15"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.0, stagger: 0.18, ease: "linear", loop: true },
    sway: 26,
    size: 30,
  },
  butterfly: {
    id: "butterfly",
    label: "Kelebek Sürüsü",
    emoji: "🦋",
    category: "burst",
    particleShape: "butterfly",
    particleCount: 16,
    colorPalette: ["#a78bfa", "#f472b6", "#fbbf24", "#67e8f9"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.5, stagger: 0.2, ease: "linear", loop: true },
    sway: 40,
    size: 28,
  },
  goldsparkle: {
    id: "goldsparkle",
    label: "Altın Parıltı",
    emoji: "✨",
    category: "burst",
    particleShape: "spark",
    particleCount: 44,
    colorPalette: ["#fde047", "#fbbf24", "#fef3c7", "#fcd34d"],
    motionPattern: "burst-radial",
    layerCount: 1,
    timing: { duration: 1.6, stagger: 0.018, ease: "power2.out" },
    spread: 58,
    size: 16,
  },
  soapbubbles: {
    id: "soapbubbles",
    label: "Sabun Köpüğü",
    emoji: "🫧",
    category: "burst",
    particleShape: "bubble",
    particleCount: 26,
    colorPalette: ["#bae6fd", "#e0f2fe", "#f8fafc", "#a5f3fc"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 3.5, stagger: 0.12, ease: "linear", loop: true },
    sway: 30,
    size: 22,
  },
  snowfall: {
    id: "snowfall",
    label: "Kar Taneleri",
    emoji: "❄️",
    category: "burst",
    particleShape: "snowflake",
    particleCount: 60,
    colorPalette: ["#ffffff", "#e0f2fe", "#bae6fd", "#f0f9ff"],
    motionPattern: "fall-down",
    layerCount: 1,
    timing: { duration: 4.5, stagger: 0.12, ease: "linear", loop: true },
    sway: 36,
    size: 20,
  },
  fireflies: {
    id: "fireflies",
    label: "Ateş Böcekleri",
    emoji: "🐝",
    category: "burst",
    particleShape: "firefly",
    particleCount: 22,
    colorPalette: ["#fde047", "#fbbf24", "#bef264", "#fef08a"],
    motionPattern: "sparkle-fade",
    layerCount: 1,
    timing: { duration: 2.8, stagger: 0.35, ease: "sine.inOut", loop: true },
    size: 10,
  },
  fireworks: {
    id: "fireworks",
    label: "Havai Fişek",
    emoji: "🎆",
    category: "burst",
    particleShape: "star",
    particleCount: 56,
    colorPalette: ["#f472b6", "#60a5fa", "#facc15", "#4ade80", "#fb923c"],
    motionPattern: "burst-radial",
    layerCount: 2,
    timing: { duration: 1.9, stagger: 0.02, ease: "power2.out" },
    spread: 70,
    size: 14,
  },

  // ---- Atmosferik / ambiyans (float-up, swirl, sparkle-fade) ----
  champagne: {
    id: "champagne",
    label: "Şampanya Köpüğü",
    emoji: "🥂",
    category: "ambient",
    particleShape: "bubble",
    particleCount: 30,
    colorPalette: ["#fde68a", "#fef3c7", "#f8fafc", "#fde047"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 3.2, stagger: 0.1, ease: "linear", loop: true },
    sway: 22,
    size: 16,
  },
  rainbow: {
    id: "rainbow",
    label: "Gökkuşağı İzi",
    emoji: "🌈",
    category: "ambient",
    particleShape: "circle",
    particleCount: 30,
    colorPalette: ["#f87171", "#fbbf24", "#4ade80", "#60a5fa", "#a78bfa"],
    motionPattern: "swirl",
    layerCount: 1,
    timing: { duration: 3.0, stagger: 0.08, ease: "linear", loop: true },
    spread: 46,
    size: 12,
  },
  envelope: {
    id: "envelope",
    label: "Uçan Mektup",
    emoji: "💌",
    category: "ambient",
    particleShape: "envelope",
    particleCount: 12,
    colorPalette: ["#fecdd3", "#fda4af", "#fff", "#ffe4e6"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.2, stagger: 0.25, ease: "linear", loop: true },
    sway: 34,
    size: 30,
  },
  shootingstar: {
    id: "shootingstar",
    label: "Yıldız Kayması",
    emoji: "🌠",
    category: "ambient",
    particleShape: "star",
    particleCount: 18,
    colorPalette: ["#ffffff", "#fef9c3", "#fde68a", "#f8fafc"],
    motionPattern: "fall-down",
    layerCount: 1,
    timing: { duration: 2.2, stagger: 0.5, ease: "linear" },
    sway: 60,
    size: 20,
  },
  candle: {
    id: "candle",
    label: "Mum Parıltısı",
    emoji: "🕯️",
    category: "ambient",
    particleShape: "light",
    particleCount: 16,
    colorPalette: ["#fde68a", "#fbbf24", "#fef3c7", "#fdba74"],
    motionPattern: "sparkle-fade",
    layerCount: 1,
    timing: { duration: 2.4, stagger: 0.3, ease: "sine.inOut", loop: true },
    size: 14,
  },
  oceanwave: {
    id: "oceanwave",
    label: "Deniz Dalgası",
    emoji: "🌊",
    category: "ambient",
    particleShape: "circle",
    particleCount: 34,
    colorPalette: ["#7dd3fc", "#38bdf8", "#e0f2fe", "#67e8f9"],
    motionPattern: "swirl",
    layerCount: 1,
    timing: { duration: 3.4, stagger: 0.09, ease: "linear", loop: true },
    spread: 50,
    size: 14,
  },
  aurora: {
    id: "aurora",
    label: "Aurora Işıkları",
    emoji: "🌌",
    category: "ambient",
    particleShape: "aurora",
    particleCount: 20,
    colorPalette: ["#34d399", "#60a5fa", "#a78bfa", "#f472b6"],
    motionPattern: "swirl",
    layerCount: 1,
    timing: { duration: 4.5, stagger: 0.15, ease: "linear", loop: true },
    spread: 55,
    size: 60,
  },
  paperbirds: {
    id: "paperbirds",
    label: "Kağıt Kuşlar",
    emoji: "🕊️",
    category: "ambient",
    particleShape: "paper-plane",
    particleCount: 14,
    colorPalette: ["#fef3c7", "#e0e7ff", "#f8fafc", "#fde68a"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 5.0, stagger: 0.3, ease: "linear", loop: true },
    sway: 50,
    size: 26,
  },
  sparkledust: {
    id: "sparkledust",
    label: "Işıltılı Toz",
    emoji: "✨",
    category: "ambient",
    particleShape: "spark",
    particleCount: 36,
    colorPalette: ["#fde047", "#fef3c7", "#fdba74", "#ffffff"],
    motionPattern: "sparkle-fade",
    layerCount: 1,
    timing: { duration: 2.2, stagger: 0.12, ease: "sine.inOut", loop: true },
    size: 14,
  },
  fireflycloud: {
    id: "fireflycloud",
    label: "Ateşböceği Bulutu",
    emoji: "🌫️",
    category: "ambient",
    particleShape: "firefly",
    particleCount: 28,
    colorPalette: ["#bef264", "#fde047", "#a3e635", "#fef9c3"],
    motionPattern: "swirl",
    layerCount: 1,
    timing: { duration: 3.6, stagger: 0.14, ease: "linear", loop: true },
    spread: 44,
    size: 10,
  },

  // ---- Davetiye açılış animasyonları için emoji tabanlı parçacıklar --------
  petalrain: {
    id: "petalrain",
    label: "Çiçek Yağmuru",
    emoji: "🌹",
    category: "ambient",
    particleShape: "petal",
    particleCount: 26,
    colorPalette: ["#fb7185", "#fda4af", "#fecdd3", "#f43f5e"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.2, stagger: 0.16, ease: "linear", loop: true },
    sway: 36,
    size: 20,
  },
  rings: {
    id: "rings",
    label: "Nişan Yüzükleri",
    emoji: "💍",
    category: "ambient",
    particleShape: "ring",
    particleCount: 12,
    colorPalette: ["#fde047", "#fef3c7", "#ffffff", "#fbbf24"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.4, stagger: 0.2, ease: "linear", loop: true },
    sway: 30,
    size: 26,
  },
  kisses: {
    id: "kisses",
    label: "Aşk Öpücükleri",
    emoji: "💋",
    category: "ambient",
    particleShape: "kiss",
    particleCount: 14,
    colorPalette: ["#f472b6", "#fb7185", "#f9a8d4", "#fecdd3"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.0, stagger: 0.18, ease: "linear", loop: true },
    sway: 34,
    size: 24,
  },
  partyfaces: {
    id: "partyfaces",
    label: "Parti Suratları",
    emoji: "🥳",
    category: "ambient",
    particleShape: "party",
    particleCount: 12,
    colorPalette: ["#facc15", "#f472b6", "#60a5fa", "#4ade80"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.2, stagger: 0.2, ease: "linear", loop: true },
    sway: 34,
    size: 28,
  },
  gifts: {
    id: "gifts",
    label: "Hediyeler",
    emoji: "🎁",
    category: "ambient",
    particleShape: "gift",
    particleCount: 10,
    colorPalette: ["#f472b6", "#fb923c", "#60a5fa", "#facc15"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.4, stagger: 0.24, ease: "linear", loop: true },
    sway: 26,
    size: 28,
  },
  cars: {
    id: "cars",
    label: "Konvoy Arabaları",
    emoji: "🚗",
    category: "ambient",
    particleShape: "car",
    particleCount: 8,
    colorPalette: ["#f87171", "#facc15", "#60a5fa", "#f8fafc"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.8, stagger: 0.3, ease: "linear", loop: true },
    sway: 20,
    size: 30,
  },
  motorcycles: {
    id: "motorcycles",
    label: "Motosiklet Konvoyu",
    emoji: "🏍️",
    category: "ambient",
    particleShape: "motorcycle",
    particleCount: 8,
    colorPalette: ["#a78bfa", "#f472b6", "#fb923c", "#f8fafc"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.8, stagger: 0.3, ease: "linear", loop: true },
    sway: 20,
    size: 28,
  },
  teddy: {
    id: "teddy",
    label: "Oyuncak Ayılar",
    emoji: "🧸",
    category: "ambient",
    particleShape: "teddy",
    particleCount: 10,
    colorPalette: ["#fbbf24", "#fca5a5", "#d6d3d1", "#fef3c7"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.2, stagger: 0.24, ease: "linear", loop: true },
    sway: 28,
    size: 28,
  },
  bridal: {
    id: "bridal",
    label: "Gelin",
    emoji: "👰",
    category: "ambient",
    particleShape: "bride",
    particleCount: 10,
    colorPalette: ["#f8fafc", "#fef9c3", "#fde68a", "#f472b6"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.6, stagger: 0.24, ease: "linear", loop: true },
    sway: 26,
    size: 26,
  },
  groom: {
    id: "groom",
    label: "Damat",
    emoji: "🤵",
    category: "ambient",
    particleShape: "groom",
    particleCount: 10,
    colorPalette: ["#e2e8f0", "#94a3b8", "#f8fafc", "#fde047"],
    motionPattern: "float-up",
    layerCount: 1,
    timing: { duration: 4.6, stagger: 0.24, ease: "linear", loop: true },
    sway: 26,
    size: 26,
  },
};

export function getEffect(id: string | undefined | null): EffectConfig {
  return (id && EFFECTS[id]) || EFFECTS.rose;
}

export function hasEffect(id: unknown): boolean {
  return typeof id === "string" && id in EFFECTS;
}

export const EFFECT_CATEGORIES: {
  id: EffectConfig["category"];
  label: string;
  emoji: string;
}[] = [
  { id: "bloom", label: "Çiçek Açma", emoji: "🌸" },
  { id: "burst", label: "Patlama & Parçacık", emoji: "💥" },
  { id: "ambient", label: "Atmosferik", emoji: "🌙" },
];

export const DEFAULT_EFFECT_BY_TEMPLATE: Record<TemplateId, EffectId> = {
  valentine: "heartburst",
  birthday: "confetti",
  newyear: "fireworks",
  special: "rose",
};
